# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'test01'
        repository: 'aak1009/pingpong'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/ping/Dockerfile'
        tags: |
          $(tag)

- stage: stage
  displayName: staging
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'appservicetest'
                appType: 'webAppContainer'
                WebAppName: 'backrule4-stage'
                DockerNamespace: 'test01'
                DockerRepository: 'aak1009/pingpong'
                DockerImageTag: '$(tag)'

